@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor LightCyan
    BorderColor DarkSlateGray
    ArrowColor DarkSlateGray
}

actor "Usuário" as usr
actor "Administrador" as admin
actor "Atleta" as atleta

' Herança de Atores
admin -up-|> usr
atleta -up-|> usr

package "SGO - Sistema de Gestão das Olimpíadas" {
    
    usecase "Autenticar no Sistema" as UC_Login
    
    usecase "Cadastrar Competição" as UC1
    usecase "Alocar Local" as UC3
    usecase "Verificar Disponibilidade de Local" as UC3_1
    
    usecase "Inscrever Atleta" as UC2
    usecase "Validar Representação de País" as UC2_1
    
    usecase "Registrar Resultados" as UC4
    usecase "Gerar Relatório de Medalhas" as UC5
    usecase "Exportar Relatório" as UC5_1
}

' Associação com o ator genérico
usr --> UC_Login

' Associações do Administrador
admin --> UC1
admin --> UC4
admin --> UC5

' Associações do Atleta
atleta --> UC2

' Regras de Inclusão (Fluxos obrigatórios)
UC1 ..> UC_Login : <<include>>
UC2 ..> UC_Login : <<include>>
UC4 ..> UC_Login : <<include>>
UC5 ..> UC_Login : <<include>>

UC1 ..> UC3 : <<include>>
UC3 ..> UC3_1 : <<include>>

UC2 ..> UC2_1 : <<include>>

' Regras de Extensão (Fluxos opcionais/condicionais)
UC5 <.. UC5_1 : <<extend>>

' Notas explicativas das regras de negócio
note bottom of UC2_1 : Garante que o atleta represente\napenas um país na modalidade.
note right of UC3_1 : Previne conflitos de horário.\nLocal exclusivo por competição.
note right of UC4 : Registra o pódio determinando:\n1º (Ouro), 2º (Prata) e 3º (Bronze).

@enduml